# Generated by Django 3.2.9 on 2022-01-20 14:07

from django.db import migrations, models
import django.db.models.deletion
import products.models
import sort_order_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the category', max_length=32)),
                ('description', models.TextField(blank=True, help_text='The description of the category', max_length=512, null=True)),
                ('available', models.BooleanField(default=False, help_text='The status of the category. Enabled / Disabled')),
                ('sort_order', sort_order_field.fields.SortOrderField(db_index=True, default=0, help_text='The order of the category in the menu')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True, auto_now=True, help_text='When was the menu created', null=True)),
                ('name', models.CharField(help_text='The name of the menu', max_length=32)),
                ('description', models.TextField(blank=True, help_text='The description of the menu', max_length=512, null=True)),
                ('available', models.BooleanField(default=False, help_text='The status of the menu. Enabled / Disabled')),
                ('modified', models.DateTimeField(auto_now=True, help_text='When was the menu modified last time', null=True)),
                ('image', models.ImageField(blank=True, help_text='The image of the menu', null=True, upload_to=products.models.menu_image_dir_path)),
                ('sort_order', sort_order_field.fields.SortOrderField(db_index=True, default=0, help_text='The order of the menu')),
            ],
            options={
                'ordering': ['-available', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ModifiersGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the Modifiers Group', max_length=32)),
                ('description', models.TextField(blank=True, help_text='The description of the Modifiers Group', max_length=512, null=True)),
                ('min_options', models.IntegerField(default=0, help_text='The minimum amount of the options can be chosen')),
                ('max_options', models.IntegerField(default=0, help_text='The maximum amount of the options can be chosen')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the product', max_length=32)),
                ('description', models.TextField(blank=True, help_text='The description of the product', max_length=512, null=True)),
                ('image', models.ImageField(blank=True, help_text='The image of the product', null=True, upload_to=products.models.product_image_dir_path)),
                ('popular', models.BooleanField(default=False, help_text='Is that product popular?')),
                ('available', models.BooleanField(default=False, help_text='The status of the product. Enabled / Disabled')),
                ('price', models.DecimalField(decimal_places=2, help_text='The price of the product', max_digits=9)),
                ('sort_order', sort_order_field.fields.SortOrderField(db_index=True, default=0, help_text='The order of the product in the menu')),
                ('category', models.ForeignKey(help_text='The Category that product belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ProductModifiers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', sort_order_field.fields.SortOrderField(db_index=True, default=0, help_text='The order of the relation.')),
                ('modifiers_group', models.ForeignKey(help_text='The ModifiersGroup of that relation.', on_delete=django.db.models.deletion.CASCADE, to='products.modifiersgroup')),
                ('product', models.ForeignKey(help_text='The product of that relation.', on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='modifiers',
            field=models.ManyToManyField(blank=True, help_text='Possible Modifiers for that product', related_name='modifiers', through='products.ProductModifiers', to='products.ModifiersGroup'),
        ),
        migrations.CreateModel(
            name='ModifiersOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the Modifiers Option', max_length=32)),
                ('price', models.DecimalField(decimal_places=2, help_text='The price of the option', max_digits=9)),
                ('in_stock', models.BooleanField(default=True, help_text='Is that option in stock?')),
                ('sort_order', sort_order_field.fields.SortOrderField(db_index=True, default=0, help_text='The order of the option in the modifiers group.')),
                ('group', models.ForeignKey(help_text='The modifiers group this option belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='options', to='products.modifiersgroup')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='menu',
            field=models.ForeignKey(help_text='The Menu this category belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='products.menu'),
        ),
    ]
