# Generated by Django 3.2.9 on 2022-01-20 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220120_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodifiers',
            name='modifiers_group',
            field=models.ForeignKey(help_text='The ModifiersGroup of that relation.', on_delete=django.db.models.deletion.CASCADE, to='products.modifiersgroup'),
        ),
        migrations.AlterField(
            model_name='productmodifiers',
            name='product',
            field=models.ForeignKey(help_text='The product of that relation.', on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
