# Generated by Django 3.2.9 on 2022-01-20 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the area (venue)', max_length=32, unique=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='WorkingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, help_text='The name of the day of the week', max_length=9)),
                ('weekday', models.IntegerField(editable=False, help_text='The number of the day of the week. 1 - Monday, 7 - Sunday')),
                ('open_24', models.BooleanField(default=False, help_text='Is the restaurant opened all the day?')),
                ('closed', models.BooleanField(default=False, help_text='Is the restaurant closed all the day?')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opens', models.TimeField(help_text='The time restaurant opens at')),
                ('closes', models.TimeField(help_text='The time restaurant closes at')),
                ('working_day', models.ForeignKey(help_text='The working day working hours are related to', on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='restaurant_info.workingday')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the table', max_length=32)),
                ('area', models.ForeignKey(help_text='The area that table belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='restaurant_info.area')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
